### ISSUE TITLE
Wich file for what ?

### ISSUE THREAD

**Issue by mblob** [FoxDenStudio/FoxCore#4]
Hi,

I don't understand what are the difference between all these files. Some of them are quiet "heavy".
Its maybe obvious for initiates but not for me :).
FoxCore-0.8.1-108-lib.jar
FoxCore-0.8.1-108-lite.jar
FoxCore-0.8.1-108-server-lib.jar
FoxCore-0.8.1-108-server-lite.jar
FoxCore-0.8.1-108-server.jar
FoxCore-0.8.1-108.jar 

Wich one should i use for a sponge forge server and a forge client ?

**Comment by gravityfox** [comment]
Don't make issues for questions. Ask on the forum.

**Comment by kinggoesgaming** [comment]
ask the questions here : https://forums.spongepowered.org/t/world-protection-foxguard-the-flexible-world-protection-solution/9952
